Update helpers.asciidoc
elastic/elasticsearch-js pull request #1310
Opened 2020-09-16 12:26 UTC by KarelVerschraegen

2020-09-16 12:26 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2020-09-21 13:49 UTC, delvedor requested changes
Thanks for contributing!
Could you please sign the CLA?

2020-09-21 13:56 UTC, KarelVerschraegen commented
> Thanks for contributing!
> Could you please sign the CLA?

I have signed it already but I have not received a confirmation message. Am I missing something or did I do something wrong?

2020-09-28 08:17 UTC, delvedor approved these changes
LGTM

2020-09-28 08:17 UTC, merged