[#1321] Fix scroll cursor leak inside searchScroll helper.
elastic/elasticsearch-js pull request #1322
Opened 2020-09-24 14:18 UTC by abarre

I didn't find a way to test this change.
The leak is not visible in the client side but only in the server side during the scroll window.

2020-09-24 14:18 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2020-09-28 08:11 UTC, delvedor requested changes
Thanks for the fix!
Regarding the test, you should add a new test case in [this file](https://github.com/elastic/elasticsearch-js/blob/master/test/unit/helpers/scroll.test.js) to verify that the last call (if the conditions are met) is a clear scroll.

2020-10-02 12:12 UTC, abarre commented
I will modify this PR in the next days. I had a quick look at the code and I see that the [test code](https://github.com/elastic/elasticsearch-js/blob/b8940533a915acedbfac0f11ebf645dad795a2a0/test/unit/helpers/scroll.test.js#L33) expect that the last request doesn't send a scroll_id in the response.
Can you confirm that this is a mistake and that in real life, all responses contain a scroll id ?

I didn't find the documentation on this point.

2020-10-07 14:26 UTC, delvedor commented
I've checked and the `scroll_id` is always present in the body, but it can change over time.
I've opened https://github.com/elastic/elasticsearch-js/pull/1331 with the fix and the updated test.
Closing this, thank you a lot for contributing!

2020-10-07 14:26 UTC, closed without merging